### ISSUE TITLE
Avoid EventEmitter memory leak warnings

### ISSUE THREAD

**Issue by danwkennedy** [hunterloftis/jackrabbit#40]
This isn't too bad but when you call consume() on an exchange with at least 10 other consumers, you will receive the following Node warning:

```
(node) warning: possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at EventEmitter.once (events.js:265:8)
    at EventEmitter.createQueue [as queue] (/var/www/sites/ms-kegactivity-receiver/node_modules/jackrabbit/lib/exchange.js:84:15)
```

It'd be nice to be able to suppress this on the exchange's instance of EventEmitter (you can do it globally but that's not a great solution IMO). I'd also be down with a "suppressWarnings" option somewhere.

**Comment by anhpham1509** [comment]
I think you can try to `setMaxListeners` to avoid this warning.

```js
const rabbit = jackrabbit(rabbitUrl);
const exchange = rabbit.default();

exchange.setMaxListeners(11); // 11 listeners
```
