### ISSUE TITLE
TypeError: Promise.defer is not a function

### ISSUE THREAD

**Issue by naartjie** [hunterloftis/jackrabbit#43]
I am getting a `TypeError: Promise.defer is not a function` when I run my consumer using [`babel-node`](https://babeljs.io/docs/usage/cli/).

I was thinking of refactoring [`exchange.js#L100-L106`](https://github.com/hunterloftis/jackrabbit/blob/d43d0919359bfd4ddad469d1dbff80aa4b716a20/lib/exchange.js#L100-L106) to `new Promise(function(resolve, reject) {...}`.

**Comment by platdesign** [comment]
+1

**Comment by shnist** [comment]
This fix resolves an error I'm experiencing when initialising JackRabbit:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: undefined is not a function
    at bindKey (/Volumes/Data/Users/aarfaber/Sites/trace-engine/server/src/node_modules/jackrabbit/lib/exchange.js:100:32)
    at Array.map (native)
    at bindKeys (/Volumes/Data/Users/aarfaber/Sites/trace-engine/server/src/node_modules/jackrabbit/lib/exchange.js:96:31)
    at EventEmitter.<anonymous> (/Volumes/Data/Users/aarfaber/Sites/trace-engine/server/src/node_modules/jackrabbit/lib/exchange.js:76:9)
    at EventEmitter.g (events.js:199:16)
    at EventEmitter.emit (events.js:129:20)
    at onQueue (/Volumes/Data/Users/aarfaber/Sites/trace-engine/server/src/node_modules/jackrabbit/lib/queue.js:133:13)
    at /Volumes/Data/Users/aarfaber/Sites/trace-engine/server/src/node_modules/jackrabbit/node_modules/amqplib/lib/callback_model.js:59:7
    at /Volumes/Data/Users/aarfaber/Sites/trace-engine/server/src/node_modules/jackrabbit/node_modules/amqplib/lib/callback_model.js:74:5
    at reply (/Volumes/Data/Users/aarfaber/Sites/trace-engine/server/src/node_modules/jackrabbit/node_modules/amqplib/lib/channel.js:100:16)
    at Channel.C.accept (/Volumes/Data/Users/aarfaber/Sites/trace-engine/server/src/node_modules/jackrabbit/node_modules/amqplib/lib/channel.js:433:12)
    at Connection.mainAccept [as accept] (/Volumes/Data/Users/aarfaber/Sites/trace-engine/server/src/node_modules/jackrabbit/node_modules/amqplib/lib/connection.js:63:33)
    at Socket.go (/Volumes/Data/Users/aarfaber/Sites/trace-engine/server/src/node_modules/jackrabbit/node_modules/amqplib/lib/connection.js:474:48)
    at Socket.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
```

**Comment by funkswing** [comment]
+1

**Comment by jaime-franco** [comment]
+1

**Comment by vancouverwill** [comment]
+1
